using System.Drawing;
using System.Drawing.Imaging;
using System.Numerics;
using System.Runtime.InteropServices;

namespace VoxelMiner.Engine;

/// PNG loading, the runtime-composited icon atlas, and the rasterized font atlas.
public static class PngLoader
{
    public static (byte[] Rgba, int Width, int Height) Load(string path)
    {
        using var bmp = new Bitmap(path);
        return ToRgba(bmp);
    }

    public static (byte[] Rgba, int Width, int Height) ToRgba(Bitmap bmp)
    {
        var data = bmp.LockBits(new Rectangle(0, 0, bmp.Width, bmp.Height), ImageLockMode.ReadOnly, PixelFormat.Format32bppArgb);
        var bgra = new byte[data.Stride * bmp.Height];
        Marshal.Copy(data.Scan0, bgra, 0, bgra.Length);
        bmp.UnlockBits(data);

        var rgba = new byte[bmp.Width * bmp.Height * 4];
        for (int y = 0; y < bmp.Height; y++)
        {
            for (int x = 0; x < bmp.Width; x++)
            {
                int src = y * data.Stride + x * 4;
                int dst = (y * bmp.Width + x) * 4;
                rgba[dst] = bgra[src + 2];     // R
                rgba[dst + 1] = bgra[src + 1]; // G
                rgba[dst + 2] = bgra[src];     // B
                rgba[dst + 3] = bgra[src + 3]; // A
            }
        }
        return (rgba, bmp.Width, bmp.Height);
    }

    /// Writes RGBA pixels to a PNG file, creating the directory if needed.
    /// Used by the texture baker to emit one PNG per swappable texture.
    public static void Save(string path, byte[] rgba, int width, int height)
    {
        using var bmp = new Bitmap(width, height, PixelFormat.Format32bppArgb);
        var data = bmp.LockBits(new Rectangle(0, 0, width, height), ImageLockMode.WriteOnly, PixelFormat.Format32bppArgb);
        var bgra = new byte[data.Stride * height];
        for (int y = 0; y < height; y++)
            for (int x = 0; x < width; x++)
            {
                int s = (y * width + x) * 4, d = y * data.Stride + x * 4;
                bgra[d] = rgba[s + 2];     // B
                bgra[d + 1] = rgba[s + 1]; // G
                bgra[d + 2] = rgba[s];     // R
                bgra[d + 3] = rgba[s + 3]; // A
            }
        Marshal.Copy(bgra, 0, data.Scan0, bgra.Length);
        bmp.UnlockBits(data);
        Directory.CreateDirectory(Path.GetDirectoryName(path));
        bmp.Save(path, ImageFormat.Png);
    }
}

/// Procedurally drawn pixels for blocks that have no PNG (torch, water,
/// vegetation).
public static class TextureGen
{
    /// Block-atlas tile index → file stem under assets/textures/blocks. The
    /// index is the tile number the mesher and BlockRegistry reference, so
    /// this array's order is the authority on tile numbering. Tiles 0..13 are
    /// split from the legacy atlas.png; 14+ are generated by GenBlockTile.
    public static readonly string[] BlockTileNames =
    {
        "grass_top", "grass_side", "dirt", "stone", "sand", "wood_side", "wood_top", "leaves",
        "coal_ore", "iron_ore", "gold_ore", "diamond_ore", "bedrock", "planks",
        "torch", "water", "tall_grass", "flower_yellow", "flower_red",
        "door_top", "door_bottom", "trapdoor",
        "chest_top", "chest_side", "chest_front",
        "furnace_top", "furnace_side", "furnace_front", "furnace_front_lit",
        "snow", "dry_grass_top", "dry_grass_side",
        "birch_side", "spruce_side", "cactus", "ice",
        "red_sand", "terracotta", "terracotta_red",
        "mycelium_top", "mycelium_side", "mushroom_cap", "mushroom_stem", "glass",
        "redstone_dust_0", "redstone_dust_1", "redstone_dust_2", "redstone_dust_3",
        "redstone_ore", "lever_base", "redstone_nub_off", "redstone_nub_on",
        "observer_front", "observer_side", "observer_back", "observer_back_lit",
        "piston_side", "piston_sticky", "honey", "slime",
        "crafting_top", "crafting_side",
    };

    /// Procedural source for generated block tiles (index >= 14). Tiles 0..13
    /// have no generator — they come from atlas.png (or a placeholder). Used
    /// only to bake a missing PNG; at runtime the file is loaded instead.
    public static byte[] GenBlockTile(int index, int size) => index switch
    {
        14 => TorchTile(size),
        15 => WaterTile(size),
        16 => GrassTile(size),
        17 => FlowerTile(size, 235, 205, 60),
        18 => FlowerTile(size, 205, 60, 60),
        19 => DoorTile(size, top: true),
        20 => DoorTile(size, top: false),
        21 => TrapdoorTileTex(size),
        22 => ChestTopTile(size),
        23 => ChestSideTile(size, front: false),
        24 => ChestSideTile(size, front: true),
        25 => FurnaceTopTile(size),
        26 => FurnaceSideTile(size, FurnaceFace.Side),
        27 => FurnaceSideTile(size, FurnaceFace.Front),
        28 => FurnaceSideTile(size, FurnaceFace.FrontLit),
        29 => SnowTileTex(size),
        30 => DryGrassTile(size, top: true),
        31 => DryGrassTile(size, top: false),
        32 => BirchTile(size),
        33 => SpruceTile(size),
        34 => CactusTileTex(size),
        35 => IceTileTex(size),
        36 => RedSandTile(size),
        37 => TerracottaTile(size, red: false),
        38 => TerracottaTile(size, red: true),
        39 => MyceliumTile(size, top: true),
        40 => MyceliumTile(size, top: false),
        41 => MushroomCapTileTex(size),
        42 => MushroomStemTile(size),
        43 => GlassTileTex(size),
        44 => DustTile(size, 0),
        45 => DustTile(size, 1),
        46 => DustTile(size, 2),
        47 => DustTile(size, 3),
        48 => RedstoneOreTileTex(size),
        49 => LeverBaseTileTex(size),
        50 => NubTile(size, on: false),
        51 => NubTile(size, on: true),
        52 => ObserverTile(size, ObserverFace.Front),
        53 => ObserverTile(size, ObserverFace.Side),
        54 => ObserverTile(size, ObserverFace.Back),
        55 => ObserverTile(size, ObserverFace.BackLit),
        56 => PistonSideTileTex(size),
        57 => PistonStickyTileTex(size),
        58 => HoneyTileTex(size),
        59 => SlimeTileTex(size),
        60 => CraftingTile(size, top: true),
        61 => CraftingTile(size, top: false),
        _ => null,
    };

    static void Put(byte[] px, int size, int x, int y, int r, int g, int b, int a = 255)
    {
        int i = (y * size + x) * 4;
        px[i] = (byte)r; px[i + 1] = (byte)g; px[i + 2] = (byte)b; px[i + 3] = (byte)a;
    }

    /// Vertical stick strip with a glowing ember top; the mesher maps the
    /// stick columns onto the little torch post's faces.
    static byte[] TorchTile(int size)
    {
        var px = new byte[size * size * 4];
        int x0 = size * 7 / 16, x1 = size * 9 / 16;
        int emberTop = size * 6 / 16, emberBot = size * 8 / 16, baseRow = size * 14 / 16;
        for (int y = emberTop; y < size; y++)
            for (int x = x0; x < x1; x++)
            {
                bool edge = x == x0;
                if (y < emberBot) Put(px, size, x, y, 255, edge ? 170 : 214, 80);      // ember
                else if (y >= baseRow) Put(px, size, x, y, 92, 62, 34);                // base
                else Put(px, size, x, y, edge ? 118 : 146, edge ? 78 : 98, 42);        // stick
            }
        return px;
    }

    static byte[] WaterTile(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                double n = Core.Noise.Hash2(x + 811, y * 31 + 47);
                int v = (int)(n * 18) - 9;
                double wave = Math.Sin((y + x * 0.5) * Math.PI / 4) * 6;
                Put(px, size, x, y, Clamp(58 + v), Clamp(120 + v + (int)wave), Clamp(214 + v));
            }
        return px;

        static int Clamp(int v) => Math.Clamp(v, 0, 255);
    }

    /// Three jagged blades of grass on a transparent background.
    static byte[] GrassTile(int size)
    {
        var px = new byte[size * size * 4]; // zero-initialized = fully transparent
        void Blade(int cx, int top, int g)
        {
            for (int y = top; y < size; y++)
            {
                int sway = (int)Math.Round(Math.Sin((y - top) * 0.9) * 1.2);
                int x = Math.Clamp(cx + sway, 0, size - 1);
                Put(px, size, x, y, 55, g, 38);
            }
        }
        Blade(size * 3 / 16, size * 4 / 16, 150);
        Blade(size * 8 / 16, size * 1 / 16, 172);
        Blade(size * 12 / 16, size * 6 / 16, 132);
        return px;
    }

    /// A short stem with a small five-petal flower head, transparent bg.
    static byte[] FlowerTile(int size, int r, int g, int b)
    {
        var px = new byte[size * size * 4];
        int cx = size / 2;
        for (int y = size * 9 / 16; y < size; y++) Put(px, size, cx, y, 60, 125, 45);
        int hy = size * 5 / 16;
        Put(px, size, cx - 1, hy, r, g, b);
        Put(px, size, cx + 1, hy, r, g, b);
        Put(px, size, cx, hy - 1, r, g, b);
        Put(px, size, cx, hy + 1, r, g, b);
        Put(px, size, cx, hy, 255, 232, 120);
        return px;
    }

    // ------------------------------------------------------------- new block tiles

    /// Vertical wooden boards with per-board shading, the base for doors.
    static void WoodBoards(byte[] px, int size, int boards, int rBase, int gBase, int bBase)
    {
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int board = x * boards / size;
                bool seam = x == board * size / boards;
                int v = (int)(Core.Noise.Hash2(x + board * 57, y + 913) * 20) - 10;
                int shade = seam ? -35 : (board % 2 == 0 ? 0 : -12);
                Put(px, size, x, y,
                    Math.Clamp(rBase + shade + v, 0, 255),
                    Math.Clamp(gBase + shade + v, 0, 255),
                    Math.Clamp(bBase + shade / 2 + v, 0, 255));
            }
    }

    /// Door texture: vertical boards with a dark frame; the top half carries
    /// a 2x2 window.
    static byte[] DoorTile(int size, bool top)
    {
        var px = new byte[size * size * 4];
        WoodBoards(px, size, 3, 132, 100, 58);
        int t = Math.Max(1, size / 16); // frame thickness
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
                if (x < t || x >= size - t || (top && y < t) || (!top && y >= size - t))
                    Put(px, size, x, y, 92, 68, 38);
        if (top)
        {
            // window: 2x2 panes centered in the upper area
            int w0 = size * 4 / 16, w1 = size * 12 / 16;
            int h0 = size * 3 / 16, h1 = size * 9 / 16;
            for (int y = h0; y < h1; y++)
                for (int x = w0; x < w1; x++)
                {
                    bool bar = x == (w0 + w1) / 2 || x == (w0 + w1) / 2 - 1 || y == (h0 + h1) / 2 || y == (h0 + h1) / 2 - 1;
                    if (bar) Put(px, size, x, y, 82, 60, 34);
                    else Put(px, size, x, y, 165, 200, 216); // glassy pane
                }
        }
        else
        {
            // door handle hint on the bottom half's edge
            int hy = size * 2 / 16;
            for (int y = hy; y < hy + Math.Max(1, size / 8); y++)
                Put(px, size, size - 3 * t, y, 60, 60, 64);
        }
        return px;
    }

    /// Trapdoor: horizontal boards with a dark border and cross brace.
    static byte[] TrapdoorTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int board = y * 4 / size;
                bool seam = y == board * size / 4;
                int v = (int)(Core.Noise.Hash2(x + 311, y + board * 71) * 18) - 9;
                int shade = seam ? -30 : (board % 2 == 0 ? 0 : -10);
                Put(px, size, x, y,
                    Math.Clamp(148 + shade + v, 0, 255),
                    Math.Clamp(112 + shade + v, 0, 255),
                    Math.Clamp(64 + shade / 2 + v, 0, 255));
            }
        int t = Math.Max(1, size / 16);
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
                if (x < t || x >= size - t || y < t || y >= size - t ||
                    Math.Abs(x - y) < t || Math.Abs(x - (size - 1 - y)) < t)
                    Put(px, size, x, y, 100, 74, 42);
        return px;
    }

    static byte[] ChestWood(int size, int rimShade)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 577, y + 133) * 16) - 8;
                bool rim = x < size / 16 + 1 || x >= size - size / 16 - 1 || y < size / 16 + 1 || y >= size - size / 16 - 1;
                int s = rim ? rimShade : 0;
                Put(px, size, x, y,
                    Math.Clamp(158 + s + v, 0, 255),
                    Math.Clamp(106 + s + v, 0, 255),
                    Math.Clamp(52 + s / 2 + v, 0, 255));
            }
        return px;
    }

    static byte[] ChestTopTile(int size) => ChestWood(size, -45);

    /// Chest side; the front adds the lid seam latch.
    static byte[] ChestSideTile(int size, bool front)
    {
        var px = ChestWood(size, -45);
        int seamY = size * 6 / 16;
        for (int x = 0; x < size; x++) Put(px, size, x, seamY, 96, 62, 30);
        if (front)
        {
            int lx0 = size * 7 / 16, lx1 = size * 9 / 16;
            for (int y = seamY - size / 16 - 1; y <= seamY + size / 16 + 1; y++)
                for (int x = lx0; x < lx1; x++)
                    Put(px, size, x, Math.Clamp(y, 0, size - 1), 190, 190, 196); // iron latch
        }
        return px;
    }

    /// Soft white snow with faint blue-gray speckles.
    static byte[] SnowTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 1223, y + 881) * 14) - 7;
                Put(px, size, x, y,
                    Math.Clamp(238 + v, 0, 255),
                    Math.Clamp(242 + v, 0, 255),
                    Math.Clamp(247 + v / 2, 0, 255));
            }
        return px;
    }

    /// Savanna ground: sun-dried yellow grass; the side variant shows dirt
    /// with a dry-grass rim on top (like the grass block's side).
    static byte[] DryGrassTile(int size, bool top)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 733, y + 577) * 26) - 13;
                bool grass = top || y < size * 3 / 16 + (int)(Core.Noise.Hash2(x + 91, 7) * (size / 8.0));
                if (grass)
                    Put(px, size, x, y,
                        Math.Clamp(178 + v, 0, 255),
                        Math.Clamp(160 + v, 0, 255),
                        Math.Clamp(74 + v / 2, 0, 255));
                else
                    Put(px, size, x, y,
                        Math.Clamp(121 + v, 0, 255),
                        Math.Clamp(85 + v, 0, 255),
                        Math.Clamp(58 + v / 2, 0, 255));
            }
        return px;
    }

    /// Birch bark: pale cream with scattered dark horizontal scars.
    static byte[] BirchTile(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 1409, y + 2203) * 16) - 8;
                bool scar = Core.Noise.Hash2(x / 3 + 631, y + 1997) > 0.88;
                if (scar) Put(px, size, x, y, 58 + v / 2, 56 + v / 2, 50);
                else Put(px, size, x, y,
                    Math.Clamp(216 + v, 0, 255), Math.Clamp(213 + v, 0, 255), Math.Clamp(202 + v, 0, 255));
            }
        return px;
    }

    /// Spruce bark: dark brown vertical striations.
    static byte[] SpruceTile(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int strip = (int)(Core.Noise.Hash2(x + 811, 0) * 24) - 12;      // per-column tone
                int v = (int)(Core.Noise.Hash2(x + 977, y + 3389) * 14) - 7;
                Put(px, size, x, y,
                    Math.Clamp(84 + strip + v, 0, 255),
                    Math.Clamp(60 + strip + v, 0, 255),
                    Math.Clamp(34 + strip / 2 + v / 2, 0, 255));
            }
        return px;
    }

    /// Cactus: green skin with darker vertical ribs and a lighter sheen.
    static byte[] CactusTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 271, y + 4111) * 14) - 7;
                bool rib = x % (size / 4) == 0;
                int s = rib ? -26 : (x % (size / 4) == size / 8 ? 10 : 0);
                Put(px, size, x, y,
                    Math.Clamp(54 + s / 2 + v, 0, 255),
                    Math.Clamp(126 + s + v, 0, 255),
                    Math.Clamp(44 + s / 2 + v, 0, 255));
            }
        return px;
    }

    /// Pale blue ice with lighter diagonal cracks.
    static byte[] IceTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 3541, y + 631) * 14) - 7;
                bool crack = (x + y * 2) % (size / 2) == 0 && Core.Noise.Hash2(x + 91, y + 55) > 0.4;
                int s = crack ? 26 : 0;
                Put(px, size, x, y,
                    Math.Clamp(158 + s + v, 0, 255),
                    Math.Clamp(196 + s + v, 0, 255),
                    Math.Clamp(238 + s / 2 + v / 2, 0, 255));
            }
        return px;
    }

    /// Badlands surface: orange-red sand speckle.
    static byte[] RedSandTile(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 5501, y + 2273) * 26) - 13;
                Put(px, size, x, y,
                    Math.Clamp(191 + v, 0, 255),
                    Math.Clamp(103 + v, 0, 255),
                    Math.Clamp(49 + v / 2, 0, 255));
            }
        return px;
    }

    /// Badlands strata: hard-baked clay with faint horizontal banding; the
    /// red variant is the darker accent band.
    static byte[] TerracottaTile(int size, bool red)
    {
        var px = new byte[size * size * 4];
        var (r, g, b) = red ? (146, 62, 41) : (172, 92, 48);
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 6151, y + 887) * 18) - 9;
                int band = (int)(Core.Noise.Hash2(0, y + 3251) * 14) - 7; // per-row tone
                Put(px, size, x, y,
                    Math.Clamp(r + band + v, 0, 255),
                    Math.Clamp(g + band + v, 0, 255),
                    Math.Clamp(b + band / 2 + v / 2, 0, 255));
            }
        return px;
    }

    /// Mushroom-island ground: purple-grey mycelium; the side variant shows
    /// dirt with a mycelium rim on top (like the grass block's side).
    static byte[] MyceliumTile(int size, bool top)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 733, y + 6577) * 24) - 12;
                bool myc = top || y < size * 3 / 16 + (int)(Core.Noise.Hash2(x + 191, 7) * (size / 8.0));
                if (myc)
                    Put(px, size, x, y,
                        Math.Clamp(122 + v, 0, 255),
                        Math.Clamp(103 + v, 0, 255),
                        Math.Clamp(128 + v, 0, 255));
                else
                    Put(px, size, x, y,
                        Math.Clamp(121 + v, 0, 255),
                        Math.Clamp(85 + v, 0, 255),
                        Math.Clamp(58 + v / 2, 0, 255));
            }
        return px;
    }

    /// Giant mushroom cap: red with 2x2 white spots.
    static byte[] MushroomCapTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 8117, y + 445) * 16) - 8;
                bool spot = Core.Noise.Hash2(x / 3 + 71, y / 3 + 313) > 0.82;
                if (spot) Put(px, size, x, y, Math.Clamp(238 + v, 0, 255), Math.Clamp(232 + v, 0, 255), Math.Clamp(224 + v, 0, 255));
                else Put(px, size, x, y, Math.Clamp(198 + v, 0, 255), Math.Clamp(48 + v / 2, 0, 255), Math.Clamp(44 + v / 2, 0, 255));
            }
        return px;
    }

    /// Giant mushroom stem: pale fibrous vertical strands.
    static byte[] MushroomStemTile(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int strip = (int)(Core.Noise.Hash2(x + 411, 3) * 16) - 8;
                int v = (int)(Core.Noise.Hash2(x + 9127, y + 719) * 10) - 5;
                Put(px, size, x, y,
                    Math.Clamp(212 + strip + v, 0, 255),
                    Math.Clamp(206 + strip + v, 0, 255),
                    Math.Clamp(193 + strip + v, 0, 255));
            }
        return px;
    }

    /// Glass: transparent pane with a pale frame and a couple of diagonal
    /// streaks; the background alpha is 0, discarded by the world shader.
    static byte[] GlassTileTex(int size)
    {
        var px = new byte[size * size * 4]; // zero-initialized = fully transparent
        int t = Math.Max(1, size / 16);
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                bool frame = x < t || x >= size - t || y < t || y >= size - t;
                bool streak = (x + y) == size / 2 + 1 || (x + y) == size / 2 + 2
                           || (x + y) == size + size / 3 || (x + y) == size + size / 3 + 1;
                if (frame) Put(px, size, x, y, 208, 226, 234);
                else if (streak) Put(px, size, x, y, 236, 246, 250, 190);
            }
        return px;
    }

    // ------------------------------------------------------------- redstone tiles

    /// Redstone dust: noisy red, four brightness bands (0 = unpowered).
    static byte[] DustTile(int size, int band)
    {
        var px = new byte[size * size * 4];
        var (r, g, b) = band switch
        {
            0 => (78, 12, 6),
            1 => (140, 22, 10),
            2 => (200, 36, 18),
            _ => (255, 60, 34),
        };
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 911, y + 1471) * 30) - 15;
                Put(px, size, x, y, Math.Clamp(r + v, 0, 255), Math.Clamp(g + v / 3, 0, 255), Math.Clamp(b + v / 4, 0, 255));
            }
        return px;
    }

    /// Stone with glowing red speckles.
    static byte[] RedstoneOreTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                if (Core.Noise.Hash2(x / 2 + 331, y / 2 + 977) > 0.82)
                    Put(px, size, x, y, 205, 30, 22);
                else StonePixel(px, size, x, y, 128);
            }
        return px;
    }

    /// Rough cobble for lever bases.
    static byte[] LeverBaseTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int cell = (int)(Core.Noise.Hash2(x / 4 + 71, y / 4 + 913) * 24) - 12;
                int v = (int)(Core.Noise.Hash2(x + 577, y + 331) * 14) - 7;
                int g = Math.Clamp(112 + cell + v, 0, 255);
                Put(px, size, x, y, g, g, g);
            }
        return px;
    }

    /// Repeater/comparator indicator nub: a redstone-torch-like knob.
    static byte[] NubTile(int size, bool on)
    {
        var px = new byte[size * size * 4];
        var (r, g, b) = on ? (255, 70, 40) : (90, 16, 10);
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 41, y + 733) * 20) - 10;
                Put(px, size, x, y, Math.Clamp(r + v, 0, 255), Math.Clamp(g + v / 3, 0, 255), Math.Clamp(b + v / 4, 0, 255));
            }
        return px;
    }

    enum ObserverFace { Front, Side, Back, BackLit }

    /// Observer faces: front carries a dark sensor slit, sides an arrow
    /// stripe, the back a redstone dot (bright while pulsing).
    static byte[] ObserverTile(int size, ObserverFace face)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
                StonePixel(px, size, x, y, y < size / 8 || y >= size - size / 8 ? 84 : 108);
        switch (face)
        {
            case ObserverFace.Front: // sensor slit across the middle
                for (int y = size * 6 / 16; y < size * 10 / 16; y++)
                    for (int x = size * 2 / 16; x < size * 14 / 16; x++)
                        Put(px, size, x, y, 30, 28, 30);
                break;
            case ObserverFace.Side: // direction stripe
                for (int y = size * 7 / 16; y < size * 9 / 16; y++)
                    for (int x = 0; x < size; x++)
                        Put(px, size, x, y, 150, 150, 152);
                break;
            case ObserverFace.Back:
            case ObserverFace.BackLit:
                var (r, g, b) = face == ObserverFace.BackLit ? (255, 60, 34) : (86, 16, 10);
                for (int y = size * 6 / 16; y < size * 10 / 16; y++)
                    for (int x = size * 6 / 16; x < size * 10 / 16; x++)
                        Put(px, size, x, y, r, g, b);
                break;
        }
        return px;
    }

    /// Piston side: wooden face strip on top of stone body.
    static byte[] PistonSideTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                if (y < size / 4)
                {
                    int v = (int)(Core.Noise.Hash2(x + 733, y + 57) * 18) - 9;
                    Put(px, size, x, y, Math.Clamp(160 + v, 0, 255), Math.Clamp(125 + v, 0, 255), Math.Clamp(75 + v / 2, 0, 255));
                }
                else StonePixel(px, size, x, y, 104);
            }
        return px;
    }

    /// Sticky piston face: wood boards with a slime pad in the middle.
    static byte[] PistonStickyTileTex(int size)
    {
        var px = new byte[size * size * 4];
        WoodBoards(px, size, 4, 160, 125, 75);
        for (int y = size * 3 / 16; y < size * 13 / 16; y++)
            for (int x = size * 3 / 16; x < size * 13 / 16; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 811, y + 373) * 20) - 10;
                Put(px, size, x, y, Math.Clamp(96 + v, 0, 255), Math.Clamp(184 + v, 0, 255), Math.Clamp(84 + v, 0, 255));
            }
        return px;
    }

    /// Crafting table: the top carries a dark 3x3 work grid; the side shows
    /// planks with two hanging tool silhouettes.
    static byte[] CraftingTile(int size, bool top)
    {
        var px = new byte[size * size * 4];
        WoodBoards(px, size, top ? 2 : 3, 160, 125, 75);
        if (top)
        {
            int g0 = size * 3 / 16, g1 = size * 13 / 16;
            int cell = (g1 - g0) / 3;
            for (int i = 0; i <= 3; i++)
            {
                for (int t = g0; t <= g1; t++)
                {
                    Put(px, size, g0 + i * cell, t, 74, 52, 30);
                    Put(px, size, t, g0 + i * cell, 74, 52, 30);
                }
            }
        }
        else
        {
            void Tool(int cx, int r, int g, int b) // small hanging silhouette
            {
                for (int y = size * 4 / 16; y < size * 7 / 16; y++)
                    for (int x = cx; x < cx + size * 3 / 16; x++)
                        Put(px, size, x, y, r, g, b);
                for (int y = size * 7 / 16; y < size * 11 / 16; y++)
                    Put(px, size, cx + size * 3 / 32, y, 96, 68, 38);
            }
            Tool(size * 2 / 16, 176, 176, 182);  // iron tool head
            Tool(size * 10 / 16, 150, 108, 60);  // wooden tool head
        }
        return px;
    }

    public static byte[] CraftingTableIcon(int size = 16) => CraftingTile(size, top: true);

    /// 16x16 icon: an angular coal lump.
    public static byte[] CoalIcon(int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int y = 4; y < 13; y++)
            for (int x = 3; x < 13; x++)
            {
                // ragged silhouette
                if (Core.Noise.Hash2(x / 2 + 11, y / 2 + 83) > 0.88) continue;
                if ((x == 3 || x == 12) && (y == 4 || y == 12)) continue;
                int v = (int)(Core.Noise.Hash2(x + 31, y + 57) * 26) - 13;
                bool sheen = Core.Noise.Hash2(x + 7, y + 3) > 0.85;
                int g = Math.Clamp((sheen ? 84 : 46) + v, 0, 255);
                Put(px, size, x, y, g, g, g + 2);
            }
        return px;
    }

    /// 16x16 icon: a metal ingot bar with a lit top face.
    public static byte[] IngotIcon(int r, int g, int b, int size = 16)
    {
        var px = new byte[size * size * 4];
        void Shade(int x, int y, float f) =>
            Put(px, size, x, y,
                Math.Clamp((int)(r * f), 0, 255), Math.Clamp((int)(g * f), 0, 255), Math.Clamp((int)(b * f), 0, 255));
        for (int y = 6; y < 12; y++)         // front face, sheared right with depth
            for (int x = 2 + (11 - y) / 2; x < 12 + (11 - y) / 2; x++)
                Shade(x, y, 1f);
        for (int x = 5; x < 15; x++) Shade(x, 5, 1.35f);  // top edge highlight
        for (int x = 4; x < 14; x++) Shade(x, 6, 1.2f);
        for (int y = 6; y < 12; y++) Shade(2 + (11 - y) / 2, y, 0.7f); // left bevel
        for (int x = 2; x < 12; x++) Shade(x, 11, 0.6f);  // bottom shadow
        return px;
    }

    /// Amber honey with lighter drips.
    static byte[] HoneyTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 337, y + 6151) * 22) - 11;
                bool blob = Core.Noise.Hash2(x / 3 + 17, y / 3 + 449) > 0.8;
                if (blob) Put(px, size, x, y, Math.Clamp(246 + v, 0, 255), Math.Clamp(196 + v, 0, 255), Math.Clamp(88 + v, 0, 255));
                else Put(px, size, x, y, Math.Clamp(224 + v, 0, 255), Math.Clamp(148 + v, 0, 255), Math.Clamp(40 + v / 2, 0, 255));
            }
        return px;
    }

    /// Green slime with a lighter inner square.
    static byte[] SlimeTileTex(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                bool inner = x >= size / 4 && x < size * 3 / 4 && y >= size / 4 && y < size * 3 / 4;
                int v = (int)(Core.Noise.Hash2(x + 4451, y + 227) * 16) - 8;
                if (inner) Put(px, size, x, y, Math.Clamp(128 + v, 0, 255), Math.Clamp(210 + v, 0, 255), Math.Clamp(116 + v, 0, 255));
                else Put(px, size, x, y, Math.Clamp(96 + v, 0, 255), Math.Clamp(178 + v, 0, 255), Math.Clamp(88 + v, 0, 255));
            }
        return px;
    }

    static void StonePixel(byte[] px, int size, int x, int y, int baseGray)
    {
        int v = (int)(Core.Noise.Hash2(x + 977, y + 389) * 26) - 13;
        int g = Math.Clamp(baseGray + v, 0, 255);
        Put(px, size, x, y, g, g, g);
    }

    static byte[] FurnaceTopTile(int size)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
                StonePixel(px, size, x, y, 120);
        return px;
    }

    enum FurnaceFace { Side, Front, FrontLit }

    static byte[] FurnaceSideTile(int size, FurnaceFace face)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
                StonePixel(px, size, x, y, y < size / 8 || y >= size - size / 8 ? 96 : 132);
        if (face != FurnaceFace.Side)
        {
            // mouth opening in the lower half
            int x0 = size * 4 / 16, x1 = size * 12 / 16;
            int y0 = size * 8 / 16, y1 = size * 14 / 16;
            for (int y = y0; y < y1; y++)
                for (int x = x0; x < x1; x++)
                {
                    if (face == FurnaceFace.FrontLit)
                    {
                        double n = Core.Noise.Hash2(x * 7 + 15, y * 5 + 91);
                        bool ember = y > y0 + (y1 - y0) / 3 || n > 0.6;
                        if (ember) Put(px, size, x, y, 255, (int)(140 + n * 90), 40);
                        else Put(px, size, x, y, 40, 22, 16);
                    }
                    else
                    {
                        Put(px, size, x, y, 28, 28, 30);
                    }
                }
        }
        return px;
    }

    /// 16x16 inventory icon for a flower, matching FlowerTile's shape.
    public static byte[] FlowerIcon(int r, int g, int b, int size = 16) => FlowerTile(size, r, g, b);

    static readonly string[] HeartShape =
    {
        ".##.##.",
        "#######",
        "#######",
        ".#####.",
        "..###..",
        "...#...",
    };

    /// 16x16 heart for the health bar. fill: 2 = full, 1 = left half, 0 = empty.
    public static byte[] HeartIcon(int fill, int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int r = 0; r < HeartShape.Length; r++)
            for (int c = 0; c < 7; c++)
            {
                if (HeartShape[r][c] != '#') continue;
                bool red = fill == 2 || (fill == 1 && c < 4);
                var (cr, cg, cb) = red ? (211, 45, 45) : (58, 58, 62);
                // highlight pixel top-left, like MC hearts
                if (red && r == 1 && c == 1) (cr, cg, cb) = (255, 150, 150);
                for (int dy = 0; dy < 2; dy++)
                    for (int dx = 0; dx < 2; dx++)
                        Put(px, size, 1 + c * 2 + dx, 2 + r * 2 + dy, cr, cg, cb);
            }
        return px;
    }
    static readonly string[] DrumstickShape =
    {
        "...####.",
        "..#MMMM#",
        ".#MLLMM#",
        ".#MLMMM#",
        ".#MMMM#.",
        ".B#MM#..",
        "BWWB#...",
        ".BB.....",
    };

    /// 16x16 drumstick for the hunger bar. fill: 2 = full, 1 = right half
    /// (the hunger bar mirrors the health bar, like Minecraft), 0 = empty.
    public static byte[] HungerIcon(int fill, int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int r = 0; r < DrumstickShape.Length; r++)
            for (int c = 0; c < 8; c++)
            {
                char ch = DrumstickShape[r][c];
                if (ch == '.') continue;
                bool filled = fill == 2 || (fill == 1 && c >= 4);
                var (cr, cg, cb) = ch switch
                {
                    '#' => filled ? (72, 42, 22) : (45, 45, 48),      // outline
                    'M' => filled ? (186, 112, 62) : (78, 78, 82),    // meat
                    'L' => filled ? (224, 158, 98) : (95, 95, 100),   // highlight
                    'W' => filled ? (238, 234, 224) : (105, 105, 110),// bone
                    _   => filled ? (168, 158, 144) : (66, 66, 70),   // bone edge
                };
                for (int dy = 0; dy < 2; dy++)
                    for (int dx = 0; dx < 2; dx++)
                        Put(px, size, c * 2 + dx, r * 2 + dy, cr, cg, cb);
            }
        return px;
    }

    /// Renders a 16x16 string pixel-map with a palette; '.' (or any char
    /// missing from the palette) stays transparent.
    static byte[] IconFromMap(string[] map, Dictionary<char, (int R, int G, int B)> pal, int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < map.Length; y++)
            for (int x = 0; x < map[y].Length; x++)
                if (pal.TryGetValue(map[y][x], out var c))
                    Put(px, size, x, y, c.R, c.G, c.B);
        return px;
    }

    static readonly string[] PorkMap =
    {
        "................",
        ".....######.....",
        "....#PPPPPP#....",
        "...#PLLPPPPP#...",
        "..#PLLPPPPPPP#..",
        "..#PLPPPPPPPP#..",
        "..#PPPPPPPPDD#..",
        "..#PPPPPPPPDD#..",
        "...#PPPPPPDD#...",
        "....#PPPPPD#....",
        ".....#PPPP#.....",
        "......BWWB......",
        ".....BWWWB......",
        ".....BWWB.......",
        "......BB........",
        "................",
    };

    /// 16x16 icon: pink porkchop with a bone stub at the bottom.
    public static byte[] RawPorkIcon() => IconFromMap(PorkMap, new()
    {
        ['#'] = (150, 74, 82),
        ['P'] = (238, 146, 152),
        ['L'] = (250, 200, 198),
        ['D'] = (205, 106, 118),
        ['W'] = (240, 236, 228),
        ['B'] = (160, 150, 140),
    });

    /// 16x16 icon: browned porkchop (furnace-cooked).
    public static byte[] CookedPorkIcon() => IconFromMap(PorkMap, new()
    {
        ['#'] = (104, 62, 32),
        ['P'] = (196, 132, 78),
        ['L'] = (226, 176, 112),
        ['D'] = (160, 98, 52),
        ['W'] = (240, 236, 228),
        ['B'] = (160, 150, 140),
    });

    static readonly string[] MuttonMap =
    {
        "................",
        "............##..",
        "...........#WW#.",
        "..........#WW#..",
        ".....####.#W#...",
        "....#MMLL#W#....",
        "...#MMMLL##.....",
        "..#MMMMMM#......",
        "..#MMMMMM#......",
        "..#DMMMM#.......",
        ".#W#DMM#........",
        "#WW##D#.........",
        "#WW#.#..........",
        ".##.............",
        "................",
        "................",
    };

    /// 16x16 icon: red mutton chunk on a diagonal bone.
    public static byte[] RawMuttonIcon() => IconFromMap(MuttonMap, new()
    {
        ['#'] = (120, 34, 38),
        ['M'] = (198, 60, 62),
        ['L'] = (232, 116, 106),
        ['D'] = (158, 40, 46),
        ['W'] = (240, 236, 228),
        ['B'] = (160, 150, 140),
    });

    /// 16x16 icon: browned mutton (furnace-cooked).
    public static byte[] CookedMuttonIcon() => IconFromMap(MuttonMap, new()
    {
        ['#'] = (96, 52, 26),
        ['M'] = (172, 108, 58),
        ['L'] = (210, 152, 92),
        ['D'] = (138, 82, 40),
        ['W'] = (240, 236, 228),
        ['B'] = (160, 150, 140),
    });

    static readonly string[] ChickenMap =
    {
        "................",
        "......####......",
        ".....#CCLL#.....",
        "....#CCCLLC#....",
        "...#CCCCCCCC#...",
        "..#CCCCCCCCCC#..",
        "..#CCCCCCCCCC#..",
        "..#DCCCCCCCCD#..",
        "..#DDCCCCCCDD#..",
        "...#DDCCCCDD#...",
        "....##DDDD##....",
        "...#W##DD#W#....",
        "...#WW####WW#...",
        "....##....##....",
        "................",
        "................",
    };

    /// 16x16 icon: whole raw chicken, pale skin with two leg bones.
    public static byte[] RawChickenIcon() => IconFromMap(ChickenMap, new()
    {
        ['#'] = (168, 110, 92),
        ['C'] = (240, 202, 172),
        ['L'] = (250, 230, 205),
        ['D'] = (216, 164, 140),
        ['W'] = (240, 236, 228),
    });

    /// 16x16 icon: golden roast chicken (furnace-cooked).
    public static byte[] CookedChickenIcon() => IconFromMap(ChickenMap, new()
    {
        ['#'] = (128, 74, 34),
        ['C'] = (214, 150, 74),
        ['L'] = (236, 188, 110),
        ['D'] = (180, 118, 52),
        ['W'] = (240, 236, 228),
    });

    /// 16x16 icon for the tall grass tuft (same art as its world tile).
    public static byte[] TallGrassIcon(int size = 16) => GrassTile(size);

    /// 16x16 inventory icon for the boat: a simple canoe profile.
    public static byte[] BoatIcon(int size = 16)
    {
        var px = new byte[size * size * 4];
        void Wood(int x, int y) => Put(px, size, x, y, 140, 97, 51);
        void Dark(int x, int y) => Put(px, size, x, y, 107, 71, 36);
        for (int x = 2; x <= 13; x++) Dark(x, 10);                  // hull bottom
        for (int x = 4; x <= 11; x++) Wood(x, 9);                   // inner floor
        foreach (int x in new[] { 2, 3, 12, 13 }) Dark(x, 8);       // rising ends
        foreach (int x in new[] { 2, 13 }) Dark(x, 7);
        for (int x = 5; x <= 10; x++) Dark(x, 11);                  // keel
        return px;
    }

    /// 16x16 inventory icon for the torch.
    public static byte[] TorchIcon(int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int y = 6; y <= 15; y++)
            for (int x = 7; x <= 8; x++)
                Put(px, size, x, y, x == 7 ? 118 : 146, x == 7 ? 78 : 98, 42);
        for (int y = 4; y <= 5; y++)
            for (int x = 7; x <= 8; x++)
                Put(px, size, x, y, 255, 214, 80);
        Put(px, size, 6, 4, 255, 150, 40); Put(px, size, 9, 4, 255, 150, 40);
        Put(px, size, 7, 3, 255, 150, 40); Put(px, size, 8, 3, 255, 150, 40);
        Put(px, size, 7, 2, 255, 200, 90); Put(px, size, 8, 2, 255, 200, 90);
        return px;
    }

    // ------------------------------------------------------------- new block icons

    static void ShadedRect(byte[] px, int size, int x0, int y0, int x1, int y1, int r, int g, int b)
    {
        for (int y = y0; y < y1; y++)
            for (int x = x0; x < x1; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 41, y + 793) * 16) - 8;
                bool edge = x == x0 || x == x1 - 1 || y == y0 || y == y1 - 1;
                int s = edge ? -40 : 0;
                Put(px, size, x, y, Math.Clamp(r + s + v, 0, 255), Math.Clamp(g + s + v, 0, 255), Math.Clamp(b + s + v, 0, 255));
            }
    }

    static (int R, int G, int B) MaterialColor(bool stone) => stone ? (138, 138, 138) : (160, 125, 75);

    /// 16x16 icon: two-step stair profile.
    public static byte[] StairsIcon(bool stone, int size = 16)
    {
        var px = new byte[size * size * 4];
        var (r, g, b) = MaterialColor(stone);
        ShadedRect(px, size, 1, 8, 15, 15, r, g, b);   // bottom step, full width
        ShadedRect(px, size, 8, 1, 15, 8, r, g, b);    // top step, right half
        return px;
    }

    /// 16x16 icon: half-block slab (horizontal or vertical).
    public static byte[] SlabIcon(bool stone, bool vertical, int size = 16)
    {
        var px = new byte[size * size * 4];
        var (r, g, b) = MaterialColor(stone);
        if (vertical) ShadedRect(px, size, 1, 1, 8, 15, r, g, b);
        else ShadedRect(px, size, 1, 8, 15, 15, r, g, b);
        return px;
    }

    /// 16x16 icon: full door seen from the front (window on top).
    public static byte[] DoorIcon(int size = 16)
    {
        var px = new byte[size * size * 4];
        ShadedRect(px, size, 4, 0, 12, 16, 132, 100, 58);
        for (int y = 2; y < 6; y++)
            for (int x = 6; x < 10; x++)
                Put(px, size, x, y, 165, 200, 216);         // window
        Put(px, size, 10, 8, 60, 60, 64);                    // handle
        Put(px, size, 10, 9, 60, 60, 64);
        return px;
    }

    public static byte[] TrapdoorIcon(int size = 16) => TrapdoorTileTex(size);
    public static byte[] ChestIcon(int size = 16) => ChestSideTile(size, front: true);
    public static byte[] FurnaceIcon(int size = 16) => FurnaceSideTile(size, FurnaceFace.Front);
    public static byte[] SnowIcon(int size = 16) => SnowTileTex(size);
    public static byte[] DryGrassIcon(int size = 16) => DryGrassTile(size, top: false);
    public static byte[] BirchIcon(int size = 16) => BirchTile(size);
    public static byte[] SpruceIcon(int size = 16) => SpruceTile(size);
    public static byte[] CactusIcon(int size = 16) => CactusTileTex(size);
    public static byte[] IceIcon(int size = 16) => IceTileTex(size);
    public static byte[] RedSandIcon(int size = 16) => RedSandTile(size);
    public static byte[] TerracottaIcon(bool red, int size = 16) => TerracottaTile(size, red);
    public static byte[] MyceliumIcon(int size = 16) => MyceliumTile(size, top: false);
    public static byte[] MushroomCapIcon(int size = 16) => MushroomCapTileTex(size);
    public static byte[] MushroomStemIcon(int size = 16) => MushroomStemTile(size);
    public static byte[] GlassIcon(int size = 16) => GlassTileTex(size);
    public static byte[] RedstoneOreIcon(int size = 16) => RedstoneOreTileTex(size);
    public static byte[] ObserverIcon(int size = 16) => ObserverTile(size, ObserverFace.Front);
    public static byte[] PistonIcon(int size = 16) => PistonSideTileTex(size);
    public static byte[] StickyPistonIcon(int size = 16) => PistonStickyTileTex(size);
    public static byte[] HoneyIcon(int size = 16) => HoneyTileTex(size);
    public static byte[] SlimeIcon(int size = 16) => SlimeTileTex(size);

    /// 16x16 icon: a pinch of redstone dust (red cross of speckles).
    public static byte[] DustIcon(int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int y = 0; y < size; y++)
            for (int x = 0; x < size; x++)
            {
                bool arm = (x >= 6 && x <= 9) || (y >= 6 && y <= 9);
                if (!arm || Core.Noise.Hash2(x + 3, y + 87) > 0.75) continue;
                int v = (int)(Core.Noise.Hash2(x + 55, y + 21) * 40) - 20;
                Put(px, size, x, y, Math.Clamp(215 + v, 0, 255), Math.Clamp(40 + v / 3, 0, 255), Math.Clamp(24 + v / 4, 0, 255));
            }
        return px;
    }

    /// 16x16 icon: cobble base with a tilted lever stick.
    public static byte[] LeverIcon(int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int y = 12; y < 15; y++)
            for (int x = 4; x < 12; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 71, y + 913) * 20) - 10;
                int g = Math.Clamp(112 + v, 0, 255);
                Put(px, size, x, y, g, g, g);
            }
        for (int i = 0; i < 8; i++) // stick leaning right
        {
            Put(px, size, 7 + i / 2, 12 - i, 146, 98, 42);
            Put(px, size, 8 + i / 2, 12 - i, 118, 78, 34);
        }
        Put(px, size, 10, 4, 200, 60, 40); // tip
        Put(px, size, 11, 4, 200, 60, 40);
        Put(px, size, 10, 5, 200, 60, 40);
        Put(px, size, 11, 5, 200, 60, 40);
        return px;
    }

    /// 16x16 icon: small stone button plate.
    public static byte[] ButtonIcon(int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int y = 5; y < 11; y++)
            for (int x = 3; x < 13; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 977, y + 389) * 20) - 10;
                bool edge = y == 5 || y == 10 || x == 3 || x == 12;
                int g = Math.Clamp((edge ? 92 : 132) + v, 0, 255);
                Put(px, size, x, y, g, g, g);
            }
        return px;
    }

    /// 16x16 icon: repeater top view (plate + two nubs); the comparator
    /// variant shows three nubs in a triangle.
    public static byte[] RepeaterIcon(bool comparator, int size = 16)
    {
        var px = new byte[size * size * 4];
        for (int y = 2; y < 14; y++)
            for (int x = 2; x < 14; x++)
            {
                int v = (int)(Core.Noise.Hash2(x + 41, y + 793) * 14) - 7;
                int g = Math.Clamp(150 + v, 0, 255);
                Put(px, size, x, y, g, g, g);
            }
        void Nub(int cx, int cy, bool lit)
        {
            for (int dy = -1; dy <= 1; dy++)
                for (int dx = -1; dx <= 1; dx++)
                    Put(px, size, cx + dx, cy + dy, lit ? 255 : 110, lit ? 70 : 22, lit ? 40 : 14);
        }
        if (comparator)
        {
            Nub(5, 11, false);
            Nub(11, 11, false);
            Nub(8, 5, true);
        }
        else
        {
            Nub(8, 4, true);
            Nub(8, 10, false);
        }
        return px;
    }

    /// 16x16 icon: two fence posts joined by two rails.
    public static byte[] FenceIcon(int size = 16)
    {
        var px = new byte[size * size * 4];
        void Bar(int x0, int y0, int x1, int y1, int shade)
        {
            for (int y = y0; y < y1; y++)
                for (int x = x0; x < x1; x++)
                {
                    int v = (int)(Core.Noise.Hash2(x + 271, y + 63) * 14) - 7;
                    Put(px, size, x, y,
                        Math.Clamp(160 + shade + v, 0, 255),
                        Math.Clamp(125 + shade + v, 0, 255),
                        Math.Clamp(75 + shade / 2 + v, 0, 255));
                }
        }
        Bar(3, 2, 6, 15, 0);    // left post
        Bar(10, 2, 13, 15, 0);  // right post
        Bar(0, 4, 16, 7, -18);  // upper rail
        Bar(0, 10, 16, 13, -18); // lower rail
        return px;
    }
}

/// All inventory icon PNGs composited into one texture, with per-item UV rects.
/// Also carries a few non-item HUD icons (hearts) under pseudo ids.
public sealed class IconAtlas
{
    public const int HeartFull = 9001;
    public const int HeartHalf = 9002;
    public const int HeartEmpty = 9003;

    public const int HungerFull = 9004;
    public const int HungerHalf = 9005;
    public const int HungerEmpty = 9006;

    public GpuTexture Texture;
    public TextureHandle Handle;
    readonly Dictionary<int, (float U0, float V0, float U1, float V1)> _uvs = new();

    /// One entry per icon: (id, file stem, generator). A null generator marks
    /// a hand-authored PNG that must already exist on disk; the rest are baked
    /// from TextureGen when their file is missing. This list is the authority
    /// on which icons exist — order only affects atlas packing, not lookup.
    static (int Id, string File, Func<byte[]> Gen)[] Manifest() => new (int, string, Func<byte[]>)[]
    {
        // hand-authored inventory art (assets/icons/*.png)
        (Core.BlockId.Grass, "grass", null), (Core.BlockId.Dirt, "dirt", null), (Core.BlockId.Stone, "stone", null),
        (Core.BlockId.Sand, "sand", null), (Core.BlockId.Wood, "wood", null), (Core.BlockId.Leaves, "leaves", null),
        (Core.BlockId.Coal, "coal_ore", null), (Core.BlockId.Iron, "iron_ore", null), (Core.BlockId.Gold, "gold_ore", null),
        (Core.BlockId.Diamond, "diamond_ore", null), (Core.BlockId.Bedrock, "bedrock", null), (Core.BlockId.Planks, "planks", null),
        (Core.ItemId.Stick, "stick", null), (Core.ItemId.WoodPick, "wooden_pickaxe", null), (Core.ItemId.StonePick, "stone_pickaxe", null),
        (Core.ItemId.IronPick, "iron_pickaxe", null), (Core.ItemId.DiamondPick, "diamond_pickaxe", null),
        (Core.ItemId.Axe, "axe", null), (Core.ItemId.Shovel, "shovel", null),

        // generated icons (baked to assets/icons/*.png on first run)
        (Core.BlockId.Torch, "torch", () => TextureGen.TorchIcon()),
        (Core.BlockId.FlowerYellow, "flower_yellow", () => TextureGen.FlowerIcon(235, 205, 60)),
        (Core.BlockId.FlowerRed, "flower_red", () => TextureGen.FlowerIcon(205, 60, 60)),
        (Core.ItemId.Boat, "boat", () => TextureGen.BoatIcon()),
        (Core.BlockId.TallGrass, "tall_grass", () => TextureGen.TallGrassIcon()),
        (HeartFull, "heart_full", () => TextureGen.HeartIcon(2)),
        (HeartHalf, "heart_half", () => TextureGen.HeartIcon(1)),
        (HeartEmpty, "heart_empty", () => TextureGen.HeartIcon(0)),
        (HungerFull, "hunger_full", () => TextureGen.HungerIcon(2)),
        (HungerHalf, "hunger_half", () => TextureGen.HungerIcon(1)),
        (HungerEmpty, "hunger_empty", () => TextureGen.HungerIcon(0)),
        (Core.ItemId.RawPigMeat, "pig_meat_raw", () => TextureGen.RawPorkIcon()),
        (Core.ItemId.RawSheepMeat, "sheep_meat_raw", () => TextureGen.RawMuttonIcon()),
        (Core.ItemId.RawChickenMeat, "chicken_meat_raw", () => TextureGen.RawChickenIcon()),
        (Core.ItemId.CookedPigMeat, "pig_meat_cooked", () => TextureGen.CookedPorkIcon()),
        (Core.ItemId.CookedSheepMeat, "sheep_meat_cooked", () => TextureGen.CookedMuttonIcon()),
        (Core.ItemId.CookedChickenMeat, "chicken_meat_cooked", () => TextureGen.CookedChickenIcon()),
        (Core.BlockId.PlankStairs, "plank_stairs", () => TextureGen.StairsIcon(stone: false)),
        (Core.BlockId.StoneStairs, "stone_stairs", () => TextureGen.StairsIcon(stone: true)),
        (Core.BlockId.PlankSlab, "plank_slab", () => TextureGen.SlabIcon(stone: false, vertical: false)),
        (Core.BlockId.StoneSlab, "stone_slab", () => TextureGen.SlabIcon(stone: true, vertical: false)),
        (Core.BlockId.PlankSlabVert, "plank_slab_vert", () => TextureGen.SlabIcon(stone: false, vertical: true)),
        (Core.BlockId.StoneSlabVert, "stone_slab_vert", () => TextureGen.SlabIcon(stone: true, vertical: true)),
        (Core.BlockId.Door, "door", () => TextureGen.DoorIcon()),
        (Core.BlockId.Trapdoor, "trapdoor", () => TextureGen.TrapdoorIcon()),
        (Core.BlockId.Chest, "chest", () => TextureGen.ChestIcon()),
        (Core.BlockId.Furnace, "furnace", () => TextureGen.FurnaceIcon()),
        (Core.BlockId.Snow, "snow", () => TextureGen.SnowIcon()),
        (Core.BlockId.DryGrass, "dry_grass", () => TextureGen.DryGrassIcon()),
        (Core.BlockId.BirchWood, "birch_wood", () => TextureGen.BirchIcon()),
        (Core.BlockId.SpruceWood, "spruce_wood", () => TextureGen.SpruceIcon()),
        (Core.BlockId.Cactus, "cactus", () => TextureGen.CactusIcon()),
        (Core.BlockId.Ice, "ice", () => TextureGen.IceIcon()),
        (Core.BlockId.RedSand, "red_sand", () => TextureGen.RedSandIcon()),
        (Core.BlockId.Terracotta, "terracotta", () => TextureGen.TerracottaIcon(red: false)),
        (Core.BlockId.TerracottaRed, "terracotta_red", () => TextureGen.TerracottaIcon(red: true)),
        (Core.BlockId.Mycelium, "mycelium", () => TextureGen.MyceliumIcon()),
        (Core.BlockId.MushroomCap, "mushroom_cap", () => TextureGen.MushroomCapIcon()),
        (Core.BlockId.MushroomStem, "mushroom_stem", () => TextureGen.MushroomStemIcon()),
        (Core.BlockId.Fence, "fence", () => TextureGen.FenceIcon()),
        (Core.BlockId.Glass, "glass", () => TextureGen.GlassIcon()),
        (Core.BlockId.RedstoneOre, "redstone_ore", () => TextureGen.RedstoneOreIcon()),
        (Core.BlockId.Dust, "redstone_dust", () => TextureGen.DustIcon()),
        (Core.BlockId.Lever, "lever", () => TextureGen.LeverIcon()),
        (Core.BlockId.Button, "button", () => TextureGen.ButtonIcon()),
        (Core.BlockId.Repeater, "repeater", () => TextureGen.RepeaterIcon(comparator: false)),
        (Core.BlockId.Comparator, "comparator", () => TextureGen.RepeaterIcon(comparator: true)),
        (Core.BlockId.Observer, "observer", () => TextureGen.ObserverIcon()),
        (Core.BlockId.Piston, "piston", () => TextureGen.PistonIcon()),
        (Core.BlockId.Piston + 12, "piston_sticky", () => TextureGen.StickyPistonIcon()), // sticky base id
        (Core.BlockId.Honey, "honey", () => TextureGen.HoneyIcon()),
        (Core.BlockId.Slime, "slime", () => TextureGen.SlimeIcon()),
        (Core.BlockId.CraftingTable, "crafting_table", () => TextureGen.CraftingTableIcon()),
        (Core.ItemId.Coal, "coal", () => TextureGen.CoalIcon()),
        (Core.ItemId.IronIngot, "iron_ingot", () => TextureGen.IngotIcon(206, 206, 212)),
        (Core.ItemId.GoldIngot, "gold_ingot", () => TextureGen.IngotIcon(240, 200, 70)),
    };

    public IconAtlas(Renderer renderer, string iconDir)
    {
        var manifest = Manifest();
        const int cell = TextureFiles.TileSize, cols = 9;
        int rows = (manifest.Length + cols - 1) / cols;
        int atlasW = cols * cell, atlasH = rows * cell;
        var pixels = new byte[atlasW * atlasH * 4];

        for (int i = 0; i < manifest.Length; i++)
        {
            var (id, file, gen) = manifest[i];
            var rgba = TextureFiles.LoadOrBake(iconDir, file, gen, cell);
            int cx = (i % cols) * cell, cy = (i / cols) * cell;
            for (int y = 0; y < cell; y++)
                for (int x = 0; x < cell; x++)
                {
                    int src = (y * cell + x) * 4, dst = ((cy + y) * atlasW + cx + x) * 4;
                    for (int c = 0; c < 4; c++) pixels[dst + c] = rgba[src + c];
                }
            _uvs[id] = ((float)cx / atlasW, (float)cy / atlasH,
                        (float)(cx + cell) / atlasW, (float)(cy + cell) / atlasH);
        }

        Texture = new GpuTexture(renderer.Ctx, pixels, atlasW, atlasH);
        Handle = renderer.RegisterTexture(Texture);
    }

    /// Writes every generated icon to its own PNG (overwriting); hand-authored
    /// entries (null generator) are left untouched. Bake-tool only.
    public static void Bake(string iconDir)
    {
        foreach (var (_, file, gen) in Manifest())
            if (gen != null) TextureFiles.Write(iconDir, file, gen(), TextureFiles.TileSize);
    }

    public void Draw(HudBatcher batch, int itemId, float x, float y, float size, float alpha = 1f)
    {
        if (!_uvs.TryGetValue(itemId, out var uv)) return;
        batch.Quad(Handle, x, y, size, size, uv.U0, uv.V0, uv.U1, uv.V1, new Vector4(1, 1, 1, alpha));
    }
}

/// ASCII 32..126 rasterized once with System.Drawing into a grid atlas.
public sealed class FontAtlas
{
    public GpuTexture Texture;
    public TextureHandle Handle;
    public readonly int CellW, CellH;
    const int Cols = 16;
    const int FirstChar = 32, LastChar = 126;
    readonly int _atlasW, _atlasH;

    public FontAtlas(Renderer renderer, float fontSize = 14f)
    {
        using var font = new Font("Consolas", fontSize, GraphicsUnit.Pixel);
        CellW = (int)Math.Ceiling(fontSize * 0.62f);
        CellH = (int)Math.Ceiling(fontSize * 1.35f);
        int rows = (LastChar - FirstChar + Cols) / Cols;
        _atlasW = Cols * CellW;
        _atlasH = rows * CellH;

        using var bmp = new Bitmap(_atlasW, _atlasH, PixelFormat.Format32bppArgb);
        using (var g = Graphics.FromImage(bmp))
        {
            g.TextRenderingHint = System.Drawing.Text.TextRenderingHint.AntiAliasGridFit;
            using var brush = new SolidBrush(Color.White);
            var format = StringFormat.GenericTypographic;
            for (int c = FirstChar; c <= LastChar; c++)
            {
                int i = c - FirstChar;
                g.DrawString(((char)c).ToString(), font, brush, (i % Cols) * CellW, (i / Cols) * CellH, format);
            }
        }
        var (rgba, w, h) = PngLoader.ToRgba(bmp);
        Texture = new GpuTexture(renderer.Ctx, rgba, w, h, srgb: false);
        Handle = renderer.RegisterTexture(Texture);
    }

    public float Measure(string text, float scale = 1f) => text.Length * CellW * scale;

    public void Draw(HudBatcher batch, string text, float x, float y, Vector4 color, float scale = 1f)
    {
        float cx = x;
        foreach (char ch in text)
        {
            int c = ch is >= (char)FirstChar and <= (char)LastChar ? ch : '?';
            int i = c - FirstChar;
            float u0 = (i % Cols) * CellW / (float)_atlasW;
            float v0 = (i / Cols) * CellH / (float)_atlasH;
            float u1 = u0 + CellW / (float)_atlasW;
            float v1 = v0 + CellH / (float)_atlasH;
            batch.Quad(Handle, cx, y, CellW * scale, CellH * scale, u0, v0, u1, v1, color);
            cx += CellW * scale;
        }
    }
}
